### ISSUE TITLE
analyzer [pinyinSimpleIndexAnalyzer] not found for field [pinyin]

### ISSUE THREAD

**Issue by jacksonrick** [liaozihong/SpringBoot-Learning#2]
报错如下：
failed to load elasticsearch nodes : org.elasticsearch.index.mapper.MapperParsingException: analyzer [pinyinSimpleIndexAnalyzer] not found for field [pinyin]

**Comment by liaozihong** [comment]
您好，请问您的elasticsearch是否安装了拼音分词elasticsearch-analysis-pinyin插件呢。
