### ISSUE TITLE
springboot-jwt的RoleMapper.xml有问题

### ISSUE THREAD

**Issue by 1340007091** [liaozihong/SpringBoot-Learning#5]
RoleAndPermissionResultMap这个resultMap配置的时候collection里也有个id字段和BaseResultMap的id字段冲突了, 导致permissions列表查询出来的结果只能有一条数据, 如果两表联查，主表和明细表的主键都是id的话，明细表的多条只能查询出来第一条.
我是这样解决的:
selectRoleOfPerm的permission表的id字段取别名为pId:
     <select id="selectRoleOfPerm" resultMap="RoleAndPermissionResultMap">
        select r.*, p.id as pId, p.*  ....
    </select>

然后将collection里的id映射改为
<id column="pId" jdbcType="INTEGER" property="id"/>

**Comment by liaozihong** [comment]
感谢反馈，确实存在id冲突的问题，已修复

**Comment by liaozihong** [comment]
done
