### ISSUE TITLE
gradle多模块协同开发问题

### ISSUE THREAD

**Issue by dousp** [liaozihong/SpringBoot-Learning#6]
请教下，开发微服务的时候，有可能团队或个人只有某几个服务的权限，现在这个项目只能一下都down下来，比如你得这个项目我只负责处理SpringBoot-Email这个服务，我只把它检出专注开发这个服务，gradle这个场景该怎么做呢？

**Comment by liaozihong** [comment]
只down特定服务的话，git好像做不到，我这个项目是为了方便才全部以子模块的形式管理的，如果是微服务开发，可以拆分为多个服务项目，分为多个git仓库，如订单服务项目，支付服务项目。

**Comment by dousp** [comment]
十分感谢
